import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f1f5f9',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 10,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
        zIndex: 10,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingRight: 12,
    },
    headerSpacer: {
        flex: 1,
    },
    scrollView: {
        flex: 1,
    },
    titleSection: {
        backgroundColor: '#fff',
        paddingHorizontal: 20,
        paddingVertical: 20,
        zIndex: 1,
    },
    title: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1e3a8a',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 14,
        color: '#475569',
        lineHeight: 20,
    },
    controlsSection: {
        backgroundColor: '#ffffff',
        paddingHorizontal: 16,
        paddingTop: 20,
        paddingBottom: 16,
        zIndex: 1000,
        elevation: 1000,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8fafc',
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#0f172a',
        marginLeft: 12,
        paddingVertical: 0,
    },
    controlsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    sortButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        shadowColor: '#1a5490',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 2,
        backgroundColor: '#ffffff',
        borderRadius: 10,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        alignSelf: 'flex-start',
    },
    sortButtonText: {
        fontSize: 14,
        color: '#1a365d',
        fontWeight: '500',
        marginHorizontal: 8,
    },
    registerButton: {
        backgroundColor: '#1e3a8a',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 8,
    },
    registerButtonText: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '600',
    },
    filterChipsContainer: {
        backgroundColor: '#ffffff',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
    },
    filterChip: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: '#f1f5f9',
        marginRight: 8,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    filterChipActive: {
        backgroundColor: '#dbeafe',
        borderColor: '#3b82f6',
    },
    filterChipText: {
        fontSize: 13,
        color: '#64748b',
        fontWeight: '600',
    },
    filterChipTextActive: {
        color: '#1e40af',
    },
    section: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1e3a8a',
        marginBottom: 16,
        paddingHorizontal: 4,
    },
    systemCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
    },
    systemImageContainer: {
        marginRight: 16,
    },
    systemImage: {
        width: 80,
        height: 70,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#fff',
    },
    systemInfo: {
        flex: 1,
    },
    statusBadgeActive: {
        alignSelf: 'flex-start',
        backgroundColor: '#d1fae5',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
        marginBottom: 8,
    },
    statusBadgePending: {
        alignSelf: 'flex-start',
        backgroundColor: '#fef3c7',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
        marginBottom: 8,
    },
    statusTextActive: {
        fontSize: 12,
        fontWeight: '600',
        color: '#047857',
    },
    statusTextPending: {
        fontSize: 12,
        fontWeight: '600',
        color: '#b45309',
    },
    systemName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#0f172a',
        marginBottom: 4,
    },
    systemId: {
        fontSize: 14,
        color: '#64748b',
        fontWeight: '500',
    },
    deleteButton: {
        padding: 8,
        borderRadius: 8,
        borderWidth: 1.5,
        borderColor: '#fee2e2',
        backgroundColor: '#fef2f2',
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
        paddingHorizontal: 32,
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#475569',
        marginTop: 16,
        marginBottom: 8,
    },
    emptyStateText: {
        fontSize: 14,
        color: '#94a3b8',
        textAlign: 'center',
        lineHeight: 20,
    },
    bottomSpacer: {
        height: 32,
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingBottom: 32,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#0f172a',
    },
    modalOption: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    modalOptionActive: {
        backgroundColor: '#f0f9ff',
    },
    modalOptionText: {
        fontSize: 16,
        color: '#334155',
        fontWeight: '500',
    },
    modalOptionTextActive: {
        color: '#1e40af',
        fontWeight: '600',
    },
    logoImage: {
        width: 60,
        height: 60,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#fff',
    },
    searchIcon: {
        fontSize: 18,
        marginRight: 10,
        color: '#94a3b8',
    },

    // FIXED: Dropdown styles - Critical z-index fixes
    dropdownContainer: {
        position: 'relative',
        zIndex: 2000,
        elevation: 2000,
    },
    dropdownMenu: {
        position: 'absolute',
        top: '100%',
        left: 0,
        right: 0,
        width: 200,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        marginTop: 8,
        shadowColor: '#1a5490',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 16,
        elevation: 8,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        maxHeight: 200,
        minWidth: 160,
        zIndex: 1000,
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
        backgroundColor: '#ffffff',
    },
    dropdownItemSelected: {
        backgroundColor: '#eff6ff',
    },
    dropdownItemText: {
        fontSize: 15,
        color: '#475569',
        fontWeight: '400',
    },
    dropdownItemTextSelected: {
        color: '#1a5490',
        fontWeight: '600',
    },
    dropdownIconRotated: {
        transform: [{ rotate: '180deg' }],
    },
    dropdownOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
        zIndex: 1500,
        elevation: 1500,
    },
});

export default styles;