import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F7FA',
    },
    header: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#ECEFF1',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
        zIndex: 100,
        position: 'relative',
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    logoContainer: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    logoImage: {
        width: '80%',
        height: '80%',
    },
    logoText: {
        fontSize: 20,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    headerTitleContainer: {
        marginLeft: 12,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A237E',
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#78909C',
        marginTop: 2,
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    iconButton: {
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: '#F5F7FA',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    notificationBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#EF5350',
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    profileButton: {
        marginLeft: 4,
        position: 'relative',
    },
    profileAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#1E88E5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileAvatarText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F7FA',
        borderRadius: 12,
        marginTop: 12,
        paddingHorizontal: 12,
        height: 44,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#263238',
        paddingRight: 30,
    },
    clearButton: {
        position: 'absolute',
        right: 12,
        padding: 4,
    },
    noResultsContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
    },
    noResultsText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#546E7A',
        marginTop: 16,
        marginBottom: 8,
    },
    noResultsSubtext: {
        fontSize: 14,
        color: '#90A4AE',
        textAlign: 'center',
    },
    scrollView: {
        flex: 1,
    },
    contentContainer: {
        padding: 16,
        paddingBottom: 90,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
        gap: 12,
    },
    section: {
        marginBottom: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#263238',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    viewAllText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#1E88E5',
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 2,
        overflow: 'hidden',
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
        paddingHorizontal: 16,
        backgroundColor: '#FFFFFF',
    },
    menuItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    iconWrapper: {
        width: 52,
        height: 52,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
    },
    iconContainer: {
        width: 44,
        height: 44,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 2,
    },
    menuTextContainer: {
        flex: 1,
    },
    menuItemTitle: {
        fontSize: 15,
        color: '#263238',
        fontWeight: '600',
    },
    menuItemSubtitle: {
        fontSize: 12,
        color: '#90A4AE',
        marginTop: 2,
    },
    divider: {
        height: 1,
        backgroundColor: '#ECEFF1',
        marginLeft: 82,
    },
    helpCard: {
        backgroundColor: '#1E88E5',
        borderRadius: 20,
        padding: 20,
        marginTop: 8,
        marginBottom: 16,
        shadowColor: '#1E88E5',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 5,
    },
    helpContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    helpTextContainer: {
        flex: 1,
    },
    helpTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 6,
    },
    helpDescription: {
        fontSize: 13,
        color: '#E3F2FD',
        marginBottom: 16,
        lineHeight: 18,
    },
    helpButton: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 20,
        alignSelf: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },
    helpButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1E88E5',
    },
    helpIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 12,
    },
    bottomNav: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderTopWidth: 1,
        borderTopColor: '#ECEFF1',
        paddingVertical: 8,
        paddingBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 8,
    },
    navItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 6,
    },
    navLabel: {
        fontSize: 11,
        color: '#90A4AE',
        marginTop: 4,
        fontWeight: '500',
    },
    navLabelActive: {
        color: '#1E88E5',
        fontWeight: '600',
    },
    dropdownMenu: {
        position: 'absolute',
        top: 52,
        right: 0,
        width: 220,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        paddingVertical: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 16,
        elevation: 12,
        zIndex: 1000,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        marginHorizontal: 4,
        marginVertical: 2,
        borderRadius: 10,
        backgroundColor: 'transparent',
    },
    dropdownItemText: {
        fontSize: 15,
        color: '#263238',
        marginLeft: 14,
        fontWeight: '500',
    },
    logoutText: {
        color: '#E53935',
        fontWeight: '500',
    },
    dropdownHeader: {
        paddingHorizontal: 12,
        paddingTop: 8,
        paddingBottom: 8,
    },
    dropdownProfileSection: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderRadius: 10,
        backgroundColor: '#F8F9FA',
    },
    dropdownAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#1E88E5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    dropdownAvatarText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    dropdownUserInfo: {
        marginLeft: 12,
        flex: 1,
    },
    dropdownUserName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#263238',
    },
    dropdownUserEmail: {
        fontSize: 12,
        color: '#78909C',
        marginTop: 2,
    },
    dropdownDivider: {
        height: 1,
        backgroundColor: '#ECEFF1',
        marginVertical: 4,
        marginHorizontal: 8,
    },
    dropdownIconWrapper: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: '#F5F7FA',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    logoutItem: {
        marginBottom: 4,
    },
    logoutIconWrapper: {
        backgroundColor: '#FFEBEE',
    },
});