import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
    },
    backButton: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1a365d',
        letterSpacing: 0.3,
    },
    headerSpacer: {
        width: 32,
    },
    scrollView: {
        flex: 1,
    },
    card: {
        backgroundColor: '#ffffff',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 12,
        padding: 20,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
    },
    cardImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain',
    },
    infoRow: {
        marginBottom: 4,
    },
    label: {
        fontSize: 13,
        color: '#64748b',
        marginBottom: 4,
        fontWeight: '500',
    },
    value: {
        fontSize: 16,
        color: '#0f172a',
        fontWeight: '600',
    },
    divider: {
        height: 1,
        backgroundColor: '#e2e8f0',
        marginVertical: 16,
    },
    sectionTitle: {
        fontSize: 17,
        fontWeight: '600',
        color: '#1a365d',
        marginLeft: 8,
    },
    imageContainer: {
        alignItems: 'center',
        marginTop: 24,
        marginBottom: 8,
    },
    imagePlaceholder: {
        width: '100%',
        height: 200,
        backgroundColor: '#eff6ff',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#dbeafe',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    editButton: {
        padding: 8,
    },
    dataGrid: {
        gap: 16,
    },
    dataRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 4,
    },
    dataLabel: {
        fontSize: 14,
        color: '#64748b',
        flex: 1,
        fontWeight: '500',
    },
    dataValue: {
        fontSize: 15,
        color: '#0f172a',
        fontWeight: '600',
        textAlign: 'right',
    },
    email: {
        color: '#3b82f6',
    },
    energyHeader: {
        marginBottom: 24,
    },
    energyTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    createButton: {
        backgroundColor: '#ffffff',
        borderWidth: 1.5,
        borderColor: '#3b82f6',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
    },
    createButtonText: {
        color: '#3b82f6',
        fontSize: 15,
        fontWeight: '600',
    },
    recordCard: {
        backgroundColor: '#f8fafc',
        borderRadius: 10,
        marginBottom: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    recordHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
    },
    recordHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    recordMonth: {
        fontSize: 15,
        fontWeight: '600',
        color: '#0f172a',
        marginLeft: 10,
    },
    recordBadge: {
        backgroundColor: '#dbeafe',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        marginLeft: 12,
    },
    recordBadgeText: {
        fontSize: 12,
        color: '#2563eb',
        fontWeight: '600',
    },
    recordIdRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    recordIdLabel: {
        fontSize: 14,
        color: '#64748b',
        fontWeight: '500',
    },
    recordIdValue: {
        fontSize: 14,
        color: '#0f172a',
        fontWeight: '600',
        marginLeft: 8,
        flex: 1,
    },
    ecpBadge: {
        backgroundColor: '#d1fae5',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
    },
    ecpText: {
        fontSize: 13,
        color: '#065f46',
        fontWeight: '600',
    },
    recordDetailsGrid: {
        gap: 12,
        marginBottom: 16,
    },
    recordDetailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    recordDetailLabel: {
        fontSize: 14,
        color: '#64748b',
        fontWeight: '500',
    },
    recordDetailValue: {
        fontSize: 14,
        color: '#0f172a',
        fontWeight: '600',
    },
    downloadButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        borderWidth: 1.5,
        borderColor: '#3b82f6',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        marginTop: 8,
    },
    downloadButtonText: {
        color: '#3b82f6',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
    bottomSpacer: {
        height: 24,
    },
    recordContent: {
        padding: 16,
        paddingTop: 8,
        backgroundColor: '#ffffff',
        borderTopWidth: 1,
        borderTopColor: '#e2e8f0',
        borderRadius: 8,
        margin: 8,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
});

export default styles;