import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F1F5F9',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 12,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    backButton: {
        paddingVertical: 8,
        paddingRight: 12,
    },
    headerSpacer: {
        width: 40,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0F172A',
        flex: 1,
        textAlign: 'center',
    },
    scrollView: {
        flex: 1,
    },
    unitIdCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderRadius: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
    },
    unitIdIcon: {
        width: 52,
        height: 52,
        borderRadius: 14,
        backgroundColor: '#EFF6FF',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    unitIdContent: {
        flex: 1,
    },
    unitIdLabel: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
        marginBottom: 4,
    },
    unitIdNumber: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0F172A',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#DCFCE7',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    statusDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#16A34A',
        marginRight: 6,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#16A34A',
    },
    menuSection: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
    },
    menuItemExpanded: {
        backgroundColor: '#F8FAFC',
    },
    menuItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    menuItemIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: '#EFF6FF',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    menuItemText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1E293B',
    },
    divider: {
        height: 1,
        backgroundColor: '#F1F5F9',
        marginHorizontal: 16,
    },
    expandedContent: {
        backgroundColor: '#F8FAFC',
        paddingTop: 16,
        paddingBottom: 20,
    },
    systemNameHeader: {
        paddingHorizontal: 16,
        paddingBottom: 12,
        marginBottom: 20,
    },
    systemNameTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0F172A',
    },
    subSection: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 12,
        marginBottom: 16,
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    subSectionTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: '#64748B',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginBottom: 16,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    infoGrid: {
        gap: 10,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 6,
        alignItems: 'flex-start',
    },
    infoLabel: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
        flex: 1,
        lineHeight: 18,
    },
    infoValue: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '600',
        flex: 1,
        textAlign: 'right',
        lineHeight: 18,
    },
    comingSoonText: {
        fontSize: 14,
        color: '#94A3B8',
        fontStyle: 'italic',
        textAlign: 'center',
        paddingVertical: 20,
    },
    controlCard: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        paddingHorizontal: 20,
        paddingVertical: 20,
        borderRadius: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
    },
    controlHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    controlTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0F172A',
        marginLeft: 12,
    },
    controlDescription: {
        fontSize: 14,
        color: '#64748B',
        lineHeight: 20,
        marginBottom: 24,
    },
    controlButtons: {
        gap: 12,
    },
    startButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#10B981',
        paddingVertical: 16,
        borderRadius: 12,
        elevation: 3,
        shadowColor: '#10B981',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    buttonDisabled: {
        backgroundColor: '#CBD5E1',
        elevation: 0,
        shadowOpacity: 0,
    },
    buttonIconCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    startButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    stopButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        paddingVertical: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E2E8F0',
    },
    stopButtonDisabled: {
        backgroundColor: '#F8FAFC',
        borderColor: '#F1F5F9',
    },
    stopButtonIconCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#F1F5F9',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    stopButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#475569',
    },
    bottomSpacer: {
        height: 32,
    },
    // Last Call Styles
    lastCallContainer: {
        paddingHorizontal: 16,
    },
    lastCallHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    lastCallTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0F172A',
        marginLeft: 8,
    },
    lastCallSection: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    lastCallRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
    },
    lastCallLabel: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
    },
    lastCallValue: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '600',
    },
    operationStatusCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    operationStatusTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#0F172A',
        marginBottom: 12,
    },
    operationStatusGrid: {
        gap: 12,
    },
    operationStatusItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    operationStatusLabel: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
    },
    operationStatusValue: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '600',
    },
    stoppedBadge: {
        backgroundColor: '#FEE2E2',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
    },
    stoppedBadgeText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#DC2626',
    },
    gaugeContainer: {
        gap: 16,
    },
    gaugeTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#0F172A',
        marginBottom: 12,
        textAlign: 'center',
    },
    gaugeCircle: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
    },
    gaugePercentage: {
        fontSize: 32,
        fontWeight: '700',
        color: '#0F172A',
        marginBottom: 8,
    },
    gaugeLabel: {
        fontSize: 11,
        color: '#94A3B8',
        fontWeight: '500',
    },
    // Customer Login Styles
    customerLoginContainer: {
        paddingHorizontal: 16,
    },
    customerLoginHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    customerLoginTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0F172A',
        marginLeft: 8,
    },
    customerLoginCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    customerLoginRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    customerLoginLabel: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
    },
    customerLoginValue: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '600',
    },
    // Status 2025 Styles
    status2025Container: {
        paddingHorizontal: 16,
    },
    status2025Header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    status2025Title: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0F172A',
        marginLeft: 8,
    },
    status2025Card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    status2025Section: {
        gap: 12,
    },
    status2025Row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 12,
    },
    status2025Label: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
        flex: 1,
        lineHeight: 18,
    },
    status2025Value: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '600',
        flex: 1,
        textAlign: 'right',
        lineHeight: 18,
    },
    status2025Divider: {
        height: 1,
        backgroundColor: '#E2E8F0',
        marginVertical: 16,
    },
    // Existing Configuration Styles
    existingConfigContainer: {
        paddingHorizontal: 16,
    },
    existingConfigHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    existingConfigTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0F172A',
        marginLeft: 8,
    },
    existingConfigCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    existingConfigRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingVertical: 8,
        gap: 12,
    },
    existingConfigLabel: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
        flex: 1,
        lineHeight: 18,
    },
    existingConfigValue: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '600',
        flex: 1,
        textAlign: 'right',
        lineHeight: 18,
    },
    existingConfigDivider: {
        height: 1,
        backgroundColor: '#F1F5F9',
        marginVertical: 4,
    },
    gaugeCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        alignItems: 'center',
    },
    gaugeWrapper: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
        paddingHorizontal: 10,
    },

    gaugeLabelBelow: {
        fontSize: 11,
        color: '#94A3B8',
        fontWeight: '500',
        marginTop: 12,
        textAlign: 'center',
    },
});

export default styles;
